ALTER TABLE CLASS
    ADD CONSTRAINT
        PK_CLASS PRIMARY KEY (CLASSNO,SECTIONID);
        

ALTER TABLE EMPLOYEE
    ADD CONSTRAINT
        PK_EMPLOYEE PRIMARY KEY (EMPID);
        
ALTER TABLE FEE
    ADD CONSTRAINT
        PK_FEE PRIMARY KEY (VOUCHER_NO); 
        
ALTER TABLE STUDENT
    ADD CONSTRAINT
        PK_STUDENT PRIMARY KEY (STDID);     
        
ALTER TABLE CARETAKER
    ADD CONSTRAINT
        PK_FEE1 PRIMARY KEY (CARETAKERID);    
          
ALTER TABLE COURSEOFFERING
    ADD CONSTRAINT
        PK_COURSEOFFERED PRIMARY KEY (COURSEID);
        
ALTER TABLE BOOK
    ADD CONSTRAINT
        PK_BOOK PRIMARY KEY (ISBN);  
        
ALTER TABLE TEACH
    ADD CONSTRAINT
        PK_TEACH PRIMARY KEY (TEACHERID);  
        
ALTER TABLE ACCOMPANY_FORM
    ADD CONSTRAINT
        PK_ACCOMPANY PRIMARY KEY(GUARDIAN_ID); 
        
        
        
        
ALTER TABLE TEACH
    ADD CONSTRAINT
        FK_CLASS FOREIGN KEY (CLASSID,SECTION) REFERENCES CLASS(CLASSNO,SECTIONID);  
              
ALTER TABLE FEE
    ADD CONSTRAINT
        FK_FEE FOREIGN KEY (STDID) REFERENCES STUDENT(STDID);  
               
ALTER TABLE STUDENT
    ADD CONSTRAINT
        FK1_STUDENT FOREIGN KEY (CLASSID,SECTION) REFERENCES CLASS(CLASSNO,SECTIONID);   
       
ALTER TABLE STUDENT
    ADD CONSTRAINT
        FK2_STUDENT FOREIGN KEY (COURSEID) REFERENCES COURSEOFFERING(COURSEID);    
              
ALTER TABLE CARETAKER
    ADD CONSTRAINT
        FK_CARETAKER FOREIGN KEY (STDID) REFERENCES STUDENT(STDID);
              
ALTER TABLE BOOK
    ADD CONSTRAINT
        FK_BOOK FOREIGN KEY (COURSEID) REFERENCES COURSEOFFERING(COURSEID);
        
        
ALTER TABLE STUDENT_HISTORY
      ADD CONSTRAINT
        FK_HISTORY FOREIGN KEY (STDID) REFERENCES STUDENT(STDID); 

ALTER TABLE ACCOMPANY_FORM
      ADD CONSTRAINT
        FK_ACCOMPANY FOREIGN KEY (STDID) REFERENCES STUDENT(STDID);
        