INSERT INTO CLASS ( CLASSNO , SECTIONID,GENDER ) VALUES (1,'A','M');
INSERT INTO CLASS ( CLASSNO , SECTIONID,GENDER ) VALUES (1,'B','F');

INSERT INTO CLASS ( CLASSNO , SECTIONID,GENDER ) VALUES (2,'A','M');
INSERT INTO CLASS ( CLASSNO , SECTIONID,GENDER ) VALUES (2,'B','F');

INSERT INTO CLASS ( CLASSNO , SECTIONID,GENDER ) VALUES (3,'A','M');
INSERT INTO CLASS ( CLASSNO , SECTIONID,GENDER ) VALUES (3,'B','F');

INSERT INTO CLASS ( CLASSNO , SECTIONID,GENDER ) VALUES (4,'A','M');
INSERT INTO CLASS ( CLASSNO , SECTIONID,GENDER ) VALUES (4,'B','F');

INSERT INTO CLASS ( CLASSNO , SECTIONID,GENDER ) VALUES (5,'A','M');
INSERT INTO CLASS ( CLASSNO , SECTIONID,GENDER ) VALUES (5,'B','F');




INSERT INTO EMPLOYEE (  EMPNAME , JOBTITLE , EMAIL , PHONENO  ) VALUES ('Kasim','Principal','kasim123@gmail.com',03215237856);
INSERT INTO EMPLOYEE (  EMPNAME , JOBTITLE , EMAIL , PHONENO  ) VALUES ('Rizwan','Vice principle','Rizwan123@gmail.com',03215142856);
INSERT INTO EMPLOYEE (  EMPNAME , JOBTITLE , EMAIL , PHONENO  ) VALUES ('Amna','HM','Amna123@gmail.com',03215234756);
INSERT INTO EMPLOYEE (  EMPNAME , JOBTITLE , EMAIL , PHONENO  ) VALUES ('Umar','Guard','Umar123@gmail.com',03215237856);
INSERT INTO EMPLOYEE (  EMPNAME , JOBTITLE , EMAIL , PHONENO  ) VALUES ('Hamza','Guard','hamza123@gmail.com',03215297856);
INSERT INTO EMPLOYEE (  EMPNAME , JOBTITLE , EMAIL , PHONENO  ) VALUES ('Naseer','Guard','Naseer123@gmail.com',03215276556);
INSERT INTO EMPLOYEE (  EMPNAME , JOBTITLE , EMAIL , PHONENO  ) VALUES ('Hassan','Guard','Hassan123@gmail.com',03215235016);
INSERT INTO EMPLOYEE (  EMPNAME , JOBTITLE , EMAIL , PHONENO  ) VALUES ('Ahsan','Clerk','Ahsan123@gmail.com',03215735856);
INSERT INTO EMPLOYEE (  EMPNAME , JOBTITLE , EMAIL , PHONENO  ) VALUES ('Zohair','Clerk','Zohair123@gmail.com',03215230626);
INSERT INTO EMPLOYEE (  EMPNAME , JOBTITLE , EMAIL , PHONENO  ) VALUES ('Ali','PA to Principle','Ali123@gmail.com',03215231236);
INSERT INTO EMPLOYEE (  EMPNAME , JOBTITLE , EMAIL , PHONENO  ) VALUES ('Ahmar','Clerk','kasim123@gmail.com',03215237856);

INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING ) VALUES ( 1,'A','Math');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING ) VALUES ( 1,'B','English');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 2,'A','Urdu');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 1,'B','Arts');

INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 2,'A','Math');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 2,'A','English');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 2,'B','Urdu');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 2,'B','Arts');

INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 3,'A''Math');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 3,'B','English Lit');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 3,'A''English Lang');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 3,'B','Urdu Lit');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 3,'A','Urdu Lang');

INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 4,'A','Math');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 4,'B','English Lit');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 4,'A','English Lang');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 4,'B','Urdu Lit');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 4,'A','Urdu Lang');

INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 5,'A','Math');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 5,'B','English Lit');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 5,'A','English Lang');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 5,'B','Urdu Lit');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 5,'A','Urdu Lang');
INSERT INTO TEACH( CLASSID ,SECTION, COURSETEACHING )VALUES ( 5,'B','Computer');
update teach
    set teacherid=teacherid+5;



INSERT INTO COURSEOFFERING( COURSENAME , MINAGE , COURSEDURATION ) VALUES ('Math',7,1);
INSERT INTO COURSEOFFERING( COURSENAME , MINAGE , COURSEDURATION ) VALUES ('English',7,1);
INSERT INTO COURSEOFFERING( COURSENAME , MINAGE , COURSEDURATION ) VALUES ('Urdu',7,1);
INSERT INTO COURSEOFFERING( COURSENAME , MINAGE , COURSEDURATION ) VALUES ('History',10,1);
INSERT INTO COURSEOFFERING( COURSENAME , MINAGE , COURSEDURATION ) VALUES ('Geography',10,1);
INSERT INTO COURSEOFFERING( COURSENAME , MINAGE , COURSEDURATION ) VALUES ('Social Studies',10,1);
INSERT INTO COURSEOFFERING( COURSENAME , MINAGE , COURSEDURATION ) VALUES ('Arts',4,1);
INSERT INTO COURSEOFFERING( COURSENAME , MINAGE , COURSEDURATION ) VALUES ('Physics',15,1);
INSERT INTO COURSEOFFERING( COURSENAME , MINAGE , COURSEDURATION ) VALUES ('Chemistry',15,1);
INSERT INTO COURSEOFFERING( COURSENAME , MINAGE , COURSEDURATION ) VALUES ('Bio',15,1);
INSERT INTO COURSEOFFERING( COURSENAME , MINAGE , COURSEDURATION ) VALUES ('Computer',5,1);

INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('hamza','1','A','1','M',TO_DATE('12/09/2016','DD/MM/YYYY'),sysdate,5,'123');
INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('ali','1','A','1','M',TO_DATE('12/08/2016','DD/MM/YYYY'),sysdate,5,'123');
INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('alia','1','B','1','F',TO_DATE('11/02/2016','DD/MM/YYYY'),sysdate,5,'123');
INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('ayesha','1','B','1','F',TO_DATE('12/03/2016','DD/MM/YYYY'),sysdate,5,'123');

INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('hamza','2','A','1','M',TO_DATE('12/02/2015','DD/MM/YYYY'),sysdate,6,'123');
INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('asif','2','A','1','M',TO_DATE('12/03/2015','DD/MM/YYYY'),sysdate,6,'123');
INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('hira','2','B','1','F',TO_DATE('12/05/2015','DD/MM/YYYY'),sysdate,6,'123');
INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('aliya','2','B','1','F',TO_DATE('12/07/2015','DD/MM/YYYY'),sysdate,6,'123');

INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('hamza','3','A','1','M',TO_DATE('12/08/2014','DD/MM/YYYY'),sysdate,7,'123');
INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('ahsan','3','A','1','M',TO_DATE('12/08/2014','DD/MM/YYYY'),sysdate,7,'123');
INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('hira','3','B','1','F',TO_DATE('12/08/2014','DD/MM/YYYY'),sysdate,7,'123');
INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('mehak','3','B','1','F',TO_DATE('12/08/2014','DD/MM/YYYY'),sysdate,7,'123');

INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('hamza','4','A','1','M',TO_DATE('12/08/2013','DD/MM/YYYY'),sysdate,8,'123');
INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('ali','4','A','1','M',TO_DATE('12/08/2013','DD/MM/YYYY'),sysdate,8,'123');
INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('alia','4','B','1','F',TO_DATE('12/08/2013','DD/MM/YYYY'),sysdate,8,'123');
INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('mehak','4','B','1','F',TO_DATE('12/08/2013','DD/MM/YYYY'),sysdate,8,'123');

INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('hamza','5','A','1','M',TO_DATE('12/08/2012','DD/MM/YYYY'),sysdate,9,'123');
INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('najeeb','5','A','1','M',TO_DATE('12/08/2012','DD/MM/YYYY'),sysdate,9,'123');
INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('benzair','5','B','1','F',TO_DATE('12/08/2012','DD/MM/YYYY'),sysdate,9,'123');
INSERT INTO STUDENT(NAME,CLASSID,SECTION,COURSEID,GENDER,DATEOFBIRTH,ADMISSION,AGE,EMAIL) VALUES('iqra','5','B','1','F',TO_DATE('12/08/2012','DD/MM/YYYY'),sysdate,9,'123');


