CREATE TABLE STUDENT (	
    STDID VARCHAR2(10)  , 
	NAME VARCHAR2(25) , 
    CLASSID VARCHAR2(10),
    SECTION VARCHAR2(10),
    COURSEID VARCHAR2(10),
	GENDER VARCHAR2(6), 
	DATEOFBIRTH DATE, 
  ADMISSION DATE,
	AGE NUMBER(3),
    EMAIL VARCHAR2(15)
);
       
CREATE TABLE EMPLOYEE(
    EMPID VARCHAR2(10),
    EMPNAME VARCHAR2(25),
    JOBTITLE VARCHAR2(15),
    EMAIL VARCHAR2(25),
    PHONENO VARCHAR2(13)
);  
       
CREATE TABLE TEACH(
    TEACHERID VARCHAR2(10),
    CLASSID VARCHAR2(10),
    SECTION VARCHAR2(10),
    COURSETEACHING VARCHAR2(50)
);
       
CREATE TABLE FEE(
     VOUCHER_NO VARCHAR2(10),
     STDID  VARCHAR2(10),
     AMOUNT NUMBER(6),
     DUEDATE DATE,
     VALIDDATE  DATE  ,
     DISCOUNT NUMBER(8)
);  

CREATE TABLE CARETAKER(
    CARETAKERID VARCHAR2(10),
    NAME VARCHAR2(25),
    CNIC VARCHAR2(18),
    STDID VARCHAR2(10),
    RELATION VARCHAR2(10),
    PHONENO VARCHAR2(13),
    EMAIL VARCHAR2(18),
    ADDRESS VARCHAR2(30)
);

CREATE TABLE COURSEOFFERING(
    COURSEID VARCHAR2(10),
    COURSENAME VARCHAR2(50),
    MINAGE NUMBER(6),
    COURSEDURATION VARCHAR2(30)
);

CREATE TABLE BOOK(
    ISBN VARCHAR2(20),
    COURSEID VARCHAR2(10),
    PUBLISHERNAME VARCHAR2(25),
    PUBLICATIONDATE DATE
);

CREATE TABLE STUDENT_HISTORY(
    STDID VARCHAR2(10),
    CLASSNO VARCHAR2(10),
    OLD_CLASS_SEC VARCHAR2(10),
    NEW_CLASS_SEC VARCHAR2(10),
    APPROVED_BY VARCHAR2(20)
);

CREATE TABLE CLASS(
    CLASSNO VARCHAR2(10),
    SECTIONID VARCHAR2(10),
    GENDER VARCHAR2(6),
    TITLE VARCHAR2(10)
);
CREATE TABLE ACCOMPANY_FORM(
   STDID VARCHAR2(10),
    GUARDIAN_ID VARCHAR2(10),
    GUARDIAN_NAME VARCHAR2(10),
    PREGNANCY_STATUS VARCHAR2(10)
);
