CREATE SEQUENCE seq_1
START WITH 1
INCREMENT BY 1
MAXVALUE 999
CYCLE;

CREATE SEQUENCE EMPLOYEE_SEQUENCE;

  CREATE OR REPLACE TRIGGER EMPLOYEE_ON_INSERT
    BEFORE INSERT ON EMPLOYEE
    FOR EACH ROW
  BEGIN
    SELECT EMPLOYEE_SEQUENCE.NEXTVAL
    INTO :NEW.EMPID
    FROM DUAL;
  END;
  
  
CREATE SEQUENCE STUDENT_SEQUENCE;

  CREATE OR REPLACE TRIGGER BOOKS_ON_INSERT
    BEFORE INSERT ON STUDENT
    FOR EACH ROW
  BEGIN
    SELECT STUDENT_SEQUENCE.NEXTVAL
    INTO :NEW.STDID
    FROM DUAL;
  END;
  
CREATE SEQUENCE TEACH_SEQUENCE;

  CREATE OR REPLACE TRIGGER TEACH_ON_INSERT
    BEFORE INSERT ON TEACH
    FOR EACH ROW
  BEGIN
    SELECT TEACH_SEQUENCE.NEXTVAL
    INTO :NEW.TEACHID
    FROM DUAL;
  END;
  
  
CREATE SEQUENCE FEE_SEQUENCE;

  CREATE OR REPLACE TRIGGER FEE_ON_INSERT
    BEFORE INSERT ON FEE
    FOR EACH ROW
  BEGIN
    SELECT FEE_SEQUENCE.NEXTVAL
    INTO :NEW.VOUCHER_NO
    FROM DUAL;
  END;
  
  
CREATE SEQUENCE CARETAKER_SEQUENCE;

  CREATE OR REPLACE TRIGGER CARETAKER_ON_INSERT
    BEFORE INSERT ON CARETAKER
    FOR EACH ROW
  BEGIN
    SELECT CARETAKER_SEQUENCE.NEXTVAL
    INTO :NEW.CARETAKERID
    FROM DUAL;
  END;
  
  
CREATE SEQUENCE COURSEOFFERING_SEQUENCE;

  CREATE OR REPLACE TRIGGER COURSEOFFERING_ON_INSERT
    BEFORE INSERT ON COURSEOFFERING
    FOR EACH ROW
  BEGIN
    SELECT COURSEOFFERING_SEQUENCE.NEXTVAL
    INTO :NEW.COURSEID
    FROM DUAL;
  END;
  